services:
  postgres_strapi_blog:
    container_name: postgres_strapi_blog
    hostname: postgres_strapi_blog
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strap-1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "C:/Users/Gabriel/OneDrive/Ambiente de Trabalho/Gabriel/Programming/docker:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
